# POST http://localhost:3000/api/auth/signup
# Content-Type: application/json

# {
#     "username": "user1",
#     "email": "user1@gmail.com",
#     "password": "esther"
# }






# POST http://localhost:3000/api/auth/signin
# Content-Type: application/json

# {
#     "email": "user1@gmail.com",
#     "password": "esther"
# }


# {
#     "email": "",
#     "password": ""
# }

PUT http://localhost:3000/api/user/update/670e40a99a6023fe8af07345
Content-Type: application/json

{
   "username": "use1"
}